<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Team;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Get the last match of a team
     *
     * @param Team $team
     *
     * @return Team
     */
    public function getLastMatch(Team $team)
    {
        $qb = $this->createQueryBuilder('g')
            ->select('g')
            ->where('g.team1 = :id')
            ->orWhere('g.team2 = :id')
            ->andWhere('g.score1 IS NOT NULL')
            ->setParameter('id',$team->getId())
            ->getQuery();
        return $qb->execute();
    }
}
